[wokwi]
version = 1
firmware = '.pio/build/my_esp32c6dev/firmware-merged.bin'
elf = '.pio/build/my_esp32c6dev/firmware-merged.bin'

[[net.forward]]
from = "localhost:8180"
to = "target:80"



# wifi SSID is Wokwi-GUEST
# https://docs.wokwi.com/guides/esp32-wifi