[wokwi]
version = 1
firmware = '.pio/build/my_esp32c3dev/merged-flash.bin'
elf = '.pio/build/my_esp32c3dev/firmware.elf'

[[net.forward]]
from = "localhost:8180"
to = "target:80"



# wifi SSID is Wokwi-GUEST
# https://docs.wokwi.com/guides/esp32-wifi